### ISSUE TITLE
Olaa Companheiro

### ISSUE THREAD

**Issue by Nurul-GC** [pangolano/todo-python#1]
Bem interessante..
Mas qual sera a utilidade deste repo..?
pretendes criar um **agendador de tarefas mesmo** ou apenas **something to exercise**!?

**Comment by joaroque** [comment]
Olá!
Irei criar um agendador de tarefas.

**Comment by Nurul-GC** [comment]
CLI ou GUI?
Posso ajudar?

**Comment by joaroque** [comment]
Pode sim! 
É CLI
